- name: Demo on conditions 
  hosts: all 
  vars:
    action: true 
  tasks: 
    - name: Run this only when the Distro is Centos
      ansible.builtin.debug:
        msg: OS Distro is {{ansible_distribution}} 
      when: ansible_distribution == "CentOS"              # this condition will run if OS is centos

    - name: Run this only when the Distro is Ubuntu
      ansible.builtin.debug:
        msg: OS Distro is {{ansible_distribution}} 
      when: ansible_distribution == "Ubuntu"         # this condition will run OS is ubuntu

    - name: Run this action
      ansible.builtin.debug:
        msg: Action is true                # this condition will if variable action is defined
      when: action           

    - name: Run this when bar is not defined 
      ansible.builtin.debug:
        msg: Bar is defined
      vars:
        bar: true
      when: bar is defined            # this condition will not executed because bar is not defined