- name: Demo on errors
  hosts: all 
  tasks:
    - name: Check Tomcat Is Running or Not 
      ansible.builtin.shell: ps -ef | grep java | grep -v grep      
      register: OUT 
      ignore_errors: true

    - name: above error ignored
      ansible.builtin.debug: 
        msg: "the above error is ignore"
