- name: Demo on loops 
  hosts: all
  become: true
  tasks:
    - name: Demo on using loops 
      ansible.builtin.debug:
        msg: "value is : {{item}}"          # Item is the keyword to represent the element in the loop as a part of the iteration
      loop:
        - 10
        - 20
        - 30 
      
    - name: Install packages in loops
      ansible.builtin.package:
        name:
          - wget                         # by this loop the packages get installed at one time
          - jq
          - nginx
          - httpd
        state: latest
      
      