- name: install nginx
  hosts: all
  remote_user: centos
  vars: 
     package: nginx
  tasks: 
    - name: Install nginx
      ansible.builtin.package:
        name: "{{package}}"
        state: present  
