- name: playing with variable
  hosts: all
  vars:                   # this is play variable declaration
    URL: google.com
    my_school: bjem
  tasks: 
    - name: printing variable
      ansible.builtin.debug:
        msg: "the url that is declared on variable is {{URL}} and i have studied in {{my_school}}"

    - name: printing variable
      ansible.builtin.debug:
        msg: "the url that is declared on variable is {{URL}} and i have studied in {{my_college}}"
      vars: 
        URL: facebook.com          # this is task level variable
        my_college: mgm