- name: playing with variable
  hosts: all
  vars: 
    URL: google.com
    my_school: bjem
  tasks: 
    - name: printing variable
      ansible.builtin.debug:
        msg: "the url that is declared on variable is {{URL}} and i have studied in {{my_school}}"