- name: Enabling nodejs18
  ansible.builtin.shell: dnf module disable nodjs -y ; dnf module enable nodejs:18 -y 

- name: Installing Nodejs18
  ansible.builtin.package:
    name: nodejs 
    state: installed 

- name: Add {{APPUSER}} 
  ansible.builtin.user:
    name: {{APPUSER}}

- name: Download and extracting {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Performing cleanup 
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent

- name: Copying {{COMPONENT}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/                   # Location of the file on the machine where you're running this cript
    dest: /home/{{APPUSER}}/{{COMPONENT}}                      # Location of the file where you want to copy this to remote server.
    remote_src: yes

- name: updating hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}
  

       