- name: changed to root user
  ansible.builtin.shell: sudo -i

- name: update 
  ansible.builtin.shell: yum update -y

- name: Configuring {{COMPONENT}} repo 
  ansible.builtin.shell: yum -y install epel-release

- name: Install Erlang and Configure RabbitMQ Repo
  ansible.builtin.shell: cd ~ && sudo wget https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_23.3.1-1~centos~7_amd64.rpm
  
- name: Install Erlang 
  ansible.builtin.shell: sudo yum update

- name: Install Erlang 
  ansible.builtin.shell: sudo yum -y install erlang
 
- name: Install RabbitMQ Repo
  ansible.builtin.shell: sudo wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.19/rabbitmq-server-3.8.19-1.el7.noarch.rpm
    

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: Starting RabbitMQ 
  ansible.builtin.shell: sudo systemctl start rabbitmq-server.service

- name: Enabling RabbitMQ 
  ansible.builtin.shell: sudo systemctl enable rabbitmq-server.service

- name: Creating {{APPUSER}} user for {{COMPONENT}}
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

